# Generated by Django 2.1.2 on 2018-11-04 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('personid', models.AutoField(default=999, primary_key=True, serialize=False)),
                ('firstname', models.CharField(default='firstname', max_length=20)),
                ('middlename', models.CharField(default='middlename', max_length=10)),
                ('lastname', models.CharField(default='lastname', max_length=30)),
                ('userid', models.IntegerField(default=999)),
                ('email', models.EmailField(default='emailfield', max_length=50)),
                ('persontype', models.CharField(blank=True, choices=[('S', 'Student'), ('F', 'Faculty'), ('O', 'Other')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('reservaionid', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('userid', models.IntegerField(default=999)),
                ('reservation_name', models.CharField(default='reservation_name', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='RoomCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='RoomStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(default=999)),
                ('reservation_made', models.ManyToManyField(to='UBReservations.Reservation')),
            ],
        ),
        migrations.CreateModel(
            name='UserCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
